#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("IoTWeight.Resource", IsApplication=true)]

namespace IoTWeight
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::IoTWeight.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::IoTWeight.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::IoTWeight.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int qrcode = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070027
			public const int BMI = 2131165223;
			
			// aapt resource value: 0x7f070009
			public const int BMI_TextView = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int BMIwikiLink = 2131165195;
			
			// aapt resource value: 0x7f07002a
			public const int ButtonLogout = 2131165226;
			
			// aapt resource value: 0x7f070035
			public const int CancelButton = 2131165237;
			
			// aapt resource value: 0x7f07000a
			public const int Category_TextView = 2131165194;
			
			// aapt resource value: 0x7f07003b
			public const int Date = 2131165243;
			
			// aapt resource value: 0x7f070033
			public const int DeleteAll = 2131165235;
			
			// aapt resource value: 0x7f07001d
			public const int DeleteButton = 2131165213;
			
			// aapt resource value: 0x7f07003d
			public const int DeleteWeighs = 2131165245;
			
			// aapt resource value: 0x7f070022
			public const int FinishActivity = 2131165218;
			
			// aapt resource value: 0x7f070025
			public const int GetStats = 2131165221;
			
			// aapt resource value: 0x7f070000
			public const int LinearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f07002e
			public const int LoginProgressCircle = 2131165230;
			
			// aapt resource value: 0x7f070008
			public const int OKButton = 2131165192;
			
			// aapt resource value: 0x7f070020
			public const int OKUpdateCaseButton = 2131165216;
			
			// aapt resource value: 0x7f070034
			public const int OKbutton = 2131165236;
			
			// aapt resource value: 0x7f07001b
			public const int ProgressCircle = 2131165211;
			
			// aapt resource value: 0x7f070038
			public const int QRresult = 2131165240;
			
			// aapt resource value: 0x7f070026
			public const int StartWeigh = 2131165222;
			
			// aapt resource value: 0x7f07001a
			public const int Text1 = 2131165210;
			
			// aapt resource value: 0x7f07003a
			public const int Weigh = 2131165242;
			
			// aapt resource value: 0x7f07001e
			public const int WeighAgainButton = 2131165214;
			
			// aapt resource value: 0x7f070039
			public const int button1 = 2131165241;
			
			// aapt resource value: 0x7f070004
			public const int buttonAddToDo = 2131165188;
			
			// aapt resource value: 0x7f07002d
			public const int buttonLoginDiffrentUser = 2131165229;
			
			// aapt resource value: 0x7f070003
			public const int buttonLoginUser = 2131165187;
			
			// aapt resource value: 0x7f07003c
			public const int checkToDoItem = 2131165244;
			
			// aapt resource value: 0x7f070017
			public const int chooseTime = 2131165207;
			
			// aapt resource value: 0x7f07003f
			public const int contentFrame = 2131165247;
			
			// aapt resource value: 0x7f07001c
			public const int currentWeigh = 2131165212;
			
			// aapt resource value: 0x7f070018
			public const int datePicker1 = 2131165208;
			
			// aapt resource value: 0x7f070030
			public const int date_display = 2131165232;
			
			// aapt resource value: 0x7f070031
			public const int date_select_button = 2131165233;
			
			// aapt resource value: 0x7f070029
			public const int debuggButton = 2131165225;
			
			// aapt resource value: 0x7f070016
			public const int displayUserTime = 2131165206;
			
			// aapt resource value: 0x7f070007
			public const int enterHeight = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int heightText = 2131165190;
			
			// aapt resource value: 0x7f070023
			public const int linearLayout1 = 2131165219;
			
			// aapt resource value: 0x7f07002f
			public const int listView = 2131165231;
			
			// aapt resource value: 0x7f070005
			public const int listViewToDo = 2131165189;
			
			// aapt resource value: 0x7f070040
			public const int menu_refresh = 2131165248;
			
			// aapt resource value: 0x7f07001f
			public const int plot_view = 2131165215;
			
			// aapt resource value: 0x7f070014
			public const int radioButtonGraph = 2131165204;
			
			// aapt resource value: 0x7f07000f
			public const int radioButtonLast3Months = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int radioButtonLast6Months = 2131165200;
			
			// aapt resource value: 0x7f07000e
			public const int radioButtonLastMonth = 2131165198;
			
			// aapt resource value: 0x7f070015
			public const int radioButtonList = 2131165205;
			
			// aapt resource value: 0x7f070011
			public const int radioButtonOther = 2131165201;
			
			// aapt resource value: 0x7f070013
			public const int radioGroupDisplayFormat = 2131165203;
			
			// aapt resource value: 0x7f07000d
			public const int radioGroupTimePeriod = 2131165197;
			
			// aapt resource value: 0x7f070037
			public const int remove_all_button = 2131165239;
			
			// aapt resource value: 0x7f070036
			public const int remove_single_button = 2131165238;
			
			// aapt resource value: 0x7f070032
			public const int singleDay = 2131165234;
			
			// aapt resource value: 0x7f070002
			public const int textNewToDo = 2131165186;
			
			// aapt resource value: 0x7f07000c
			public const int textView1 = 2131165196;
			
			// aapt resource value: 0x7f070012
			public const int textView2 = 2131165202;
			
			// aapt resource value: 0x7f07002b
			public const int textView3 = 2131165227;
			
			// aapt resource value: 0x7f070001
			public const int textViewTitle = 2131165185;
			
			// aapt resource value: 0x7f07002c
			public const int tv_login_msg = 2131165228;
			
			// aapt resource value: 0x7f070019
			public const int tv_servname = 2131165209;
			
			// aapt resource value: 0x7f070028
			public const int update = 2131165224;
			
			// aapt resource value: 0x7f070021
			public const int updateButton = 2131165217;
			
			// aapt resource value: 0x7f07003e
			public const int updateHeight = 2131165246;
			
			// aapt resource value: 0x7f070024
			public const int welcomeText = 2131165220;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Activity_To_Do = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BMIview = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ChooseDisplay = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int deleteWeighs = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int DisplayWeigh = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Graphs = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int heightView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int InsertWeights = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int LogInWelcome = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Main = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int multipleColumnsLayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int PickDate = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int PickDateViewVer2 = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int QRView = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int row = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Row_List_To_Do = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int updateProfile = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int zxingscanneractivitylayout = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int zxingscannerfragmentlayout = 2130903058;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int activity_main = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int add_button_text = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int add_textbox_hint = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int checkbox_text = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int login_button_text = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int login_diff_button_text = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int menu_refresh = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int mobile_services = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int openCamera = 2130968584;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050006
			public const int AppBaseTheme = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int AppTheme = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int DefButton = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int DefH1 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int DefH2 = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int DefLayout = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int DefText = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int SpreadButton = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
