#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("weighJune28.Resource", IsApplication=true)]

namespace weighJune28
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07001a
			public const int BMI = 2131165210;
			
			// aapt resource value: 0x7f070009
			public const int BMI_TextView = 2131165193;
			
			// aapt resource value: 0x7f070022
			public const int Date = 2131165218;
			
			// aapt resource value: 0x7f070018
			public const int GetStats = 2131165208;
			
			// aapt resource value: 0x7f070000
			public const int LinearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int OKButton = 2131165191;
			
			// aapt resource value: 0x7f070014
			public const int ProgressCircle = 2131165204;
			
			// aapt resource value: 0x7f070008
			public const int RecomendedBMI = 2131165192;
			
			// aapt resource value: 0x7f070019
			public const int StartWeigh = 2131165209;
			
			// aapt resource value: 0x7f070013
			public const int Text1 = 2131165203;
			
			// aapt resource value: 0x7f070021
			public const int Weigh = 2131165217;
			
			// aapt resource value: 0x7f07001e
			public const int btn_takepic = 2131165214;
			
			// aapt resource value: 0x7f070003
			public const int buttonAddToDo = 2131165187;
			
			// aapt resource value: 0x7f07001b
			public const int buttonLoginUser = 2131165211;
			
			// aapt resource value: 0x7f070023
			public const int checkToDoItem = 2131165219;
			
			// aapt resource value: 0x7f070015
			public const int currentWeigh = 2131165205;
			
			// aapt resource value: 0x7f070006
			public const int enterHeight = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int heightText = 2131165189;
			
			// aapt resource value: 0x7f07001f
			public const int img_showpic = 2131165215;
			
			// aapt resource value: 0x7f070017
			public const int linearLayout1 = 2131165207;
			
			// aapt resource value: 0x7f07001d
			public const int listView = 2131165213;
			
			// aapt resource value: 0x7f070004
			public const int listViewToDo = 2131165188;
			
			// aapt resource value: 0x7f070024
			public const int menu_refresh = 2131165220;
			
			// aapt resource value: 0x7f070016
			public const int plot_view = 2131165206;
			
			// aapt resource value: 0x7f070011
			public const int radioButtonGraph = 2131165201;
			
			// aapt resource value: 0x7f07000d
			public const int radioButtonLast3Months = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int radioButtonLast6Months = 2131165198;
			
			// aapt resource value: 0x7f07000c
			public const int radioButtonLastMonth = 2131165196;
			
			// aapt resource value: 0x7f070012
			public const int radioButtonList = 2131165202;
			
			// aapt resource value: 0x7f07001c
			public const int radioGroup1 = 2131165212;
			
			// aapt resource value: 0x7f070010
			public const int radioGroupDisplayFormat = 2131165200;
			
			// aapt resource value: 0x7f07000b
			public const int radioGroupTimePeriod = 2131165195;
			
			// aapt resource value: 0x7f070002
			public const int textNewToDo = 2131165186;
			
			// aapt resource value: 0x7f07000a
			public const int textView1 = 2131165194;
			
			// aapt resource value: 0x7f07000f
			public const int textView2 = 2131165199;
			
			// aapt resource value: 0x7f070001
			public const int textViewTitle = 2131165185;
			
			// aapt resource value: 0x7f070020
			public const int tv_result = 2131165216;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Activity_To_Do = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BMIview = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ChooseDisplay = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int DisplayWeigh = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Graphs = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int LogInWelcome = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int multipleColumnsLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int QRView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int row = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Row_List_To_Do = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int activity_main = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int add_button_text = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int add_textbox_hint = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int checkbox_text = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int login_button_text = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int menu_refresh = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int mobile_services = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int openCamera = 2130968583;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AppBaseTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int AppTheme = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
